In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
%cd "/content/drive/MyDrive/NLPFinal/FLive"

/content/drive/MyDrive/Colab Notebooks/iNeuron/DL/Flive/NLP


In [ ]:
try:
  from transformers import pipeline
except Exception as e:
  print(e)
  print("installing...")
  !pip install datasets transformers[sentencepiece] -q
  from transformers import pipeline

No module named 'transformers'
installing...
     |████████████████████████████████| 365 kB 14.9 MB/s 
     |████████████████████████████████| 4.7 MB 87.4 MB/s 
     |████████████████████████████████| 115 kB 89.6 MB/s 
     |████████████████████████████████| 141 kB 65.6 MB/s 
     |████████████████████████████████| 101 kB 11.7 MB/s 
     |████████████████████████████████| 212 kB 91.0 MB/s 
     |████████████████████████████████| 596 kB 66.3 MB/s 
     |████████████████████████████████| 127 kB 75.4 MB/s 
     |████████████████████████████████| 6.6 MB 57.8 MB/s 
     |████████████████████████████████| 1.3 MB 64.4 MB/s 


In [ ]:
classifier = pipeline("sentiment-analysis")
classifier("I love my country")

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


[{'label': 'POSITIVE', 'score': 0.9998471736907959}]

In [ ]:
from transformers import AutoTokenizer

In [ ]:
ckpt = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer=AutoTokenizer.from_pretrained(ckpt)

In [ ]:
inputs = "I love my country"

In [ ]:
tokenizer(inputs)  # attention_mask: more attention/weightage given to certain words

{'input_ids': [101, 1045, 2293, 2026, 2406, 102], 'attention_mask': [1, 1, 1, 1, 1, 1]}

In [ ]:
batch_input = ["I love my country",
               "I am Sunny and I work in iNeuron"]

In [ ]:
out = tokenizer(batch_input, padding=True)
out

{'input_ids': [[101, 1045, 2293, 2026, 2406, 102, 0, 0, 0, 0, 0, 0], [101, 1045, 2572, 11559, 1998, 1045, 2147, 1999, 1999, 11236, 2239, 102]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]}

In [ ]:
type(out)

transformers.tokenization_utils_base.BatchEncoding

In [ ]:
out_pytorch_tensors = tokenizer(batch_input, padding=True, return_tensors="pt")
out_pytorch_tensors

{'input_ids': tensor([[  101,  1045,  2293,  2026,  2406,   102,     0,     0,     0,     0,
             0,     0],
        [  101,  1045,  2572, 11559,  1998,  1045,  2147,  1999,  1999, 11236,
          2239,   102]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [ ]:
out_TF_tensors = tokenizer(batch_input, padding=True, return_tensors="tf")
out_TF_tensors # returns tensors type

{'input_ids': <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[  101,  1045,  2293,  2026,  2406,   102,     0,     0,     0,
            0,     0,     0],
       [  101,  1045,  2572, 11559,  1998,  1045,  2147,  1999,  1999,
        11236,  2239,   102]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [ ]:
from transformers import AutoModel

In [ ]:
model_ckpt = AutoModel.from_pretrained(ckpt)

Some weights of the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing DistilBertModel: ['classifier.weight', 'pre_classifier.weight', 'classifier.bias', 'pre_classifier.bias']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [ ]:
model_ckpt

DistilBertModel(
  (embeddings): Embeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (transformer): Transformer(
    (layer): ModuleList(
      (0): TransformerBlock(
        (attention): MultiHeadSelfAttention(
          (dropout): Dropout(p=0.1, inplace=False)
          (q_lin): Linear(in_features=768, out_features=768, bias=True)
          (k_lin): Linear(in_features=768, out_features=768, bias=True)
          (v_lin): Linear(in_features=768, out_features=768, bias=True)
          (out_lin): Linear(in_features=768, out_features=768, bias=True)
        )
        (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        (ffn): FFN(
          (dropout): Dropout(p=0.1, inplace=False)
          (lin1): Linear(in_features=768, out_features=3072, bias=True)
          (lin2): Linear(i

In [ ]:
logits = model_ckpt(**out_pytorch_tensors)
logits

BaseModelOutput([('last_hidden_state',
                  tensor([[[ 0.4521,  0.2584,  0.0448,  ...,  0.4836,  0.8697, -0.2664],
                           [ 0.5710,  0.4134,  0.0491,  ...,  0.5090,  0.7748, -0.2068],
                           [ 0.8872,  0.5492,  0.2826,  ...,  0.3853,  0.8563, -0.2052],
                           ...,
                           [ 0.1293,  0.1981, -0.0614,  ...,  0.5446,  0.7708, -0.1253],
                           [ 0.0972,  0.2152, -0.0695,  ...,  0.5433,  0.7558, -0.1254],
                           [ 0.2259,  0.4079, -0.0303,  ...,  0.4686,  0.7017, -0.1708]],
                  
                          [[ 0.5704, -0.0348,  0.5274,  ...,  0.0961,  0.9891, -0.4406],
                           [ 0.9509,  0.2351,  0.2996,  ...,  0.2680,  0.9693, -0.3488],
                           [ 0.7480,  0.4432,  0.4767,  ...,  0.1815,  0.6351, -0.2903],
                           ...,
                           [-0.4420, -0.0161,  0.6879,  ..., -0.0880,  0.803

In [ ]:
batch_size, sequence_len, Hidden_state= logits["last_hidden_state"].shape
batch_size, sequence_len, Hidden_state

(2, 12, 768)

In [ ]:
from transformers import AutoModelForSequenceClassification
model_2 = AutoModelForSequenceClassification.from_pretrained(ckpt)
pred = model_2(**out_pytorch_tensors) 
pred

SequenceClassifierOutput([('logits', tensor([[-4.2268,  4.5594],
                                   [-3.8146,  4.0510]], grad_fn=<AddmmBackward0>))])

In [ ]:
import torch
pred_prob = torch.nn.functional.softmax(pred.logits, dim=1)
print(pred_prob)

tensor([[1.5280e-04, 9.9985e-01],
        [3.8356e-04, 9.9962e-01]], grad_fn=<SoftmaxBackward0>)


In [ ]:
model_2.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}

In [ ]:
torch.argmax(pred_prob, dim=-1)

tensor([1, 1])